kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  namespace: chat-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce 
  storageClassName: "mongodb-storage-class"
  hostPath: 
    path: /data
  
