name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Frontend Compilation
        run: |
          cd frontend
          find . -name "*.js" -exec node --check {} +

      - name: Backend Compilation
        run: |
          cd backend
          find . -name "*.js" -exec node --check {} +

  trivy_fs_scanning:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: trivy scanning
        uses: aquasecurity/trivy-action@0.28.0
        with:
            scan-type: 'fs'
            scan-ref: '.'   # path which we want to scan
            format: 'table'  # result in table format
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

  sonar-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SonarQube Scan (frontend)
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: frontend
        args: >
          -Dsonar.projectKey=myorg_frontend
          -Dsonar.projectName=myorg_frontend
          -Dsonar.sources=.
          -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Debug Sonar secrets (frontend)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        if [ -z "$SONAR_TOKEN" ]; then echo "SONAR_TOKEN missing"; else echo "SONAR_TOKEN OK"; fi
        if [ -z "$SONAR_HOST_URL" ]; then echo "SONAR_HOST_URL missing"; else echo "SONAR_HOST_URL OK"; fi

  sonar-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SonarQube Scan (backend)
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: backend
        args: >
          -Dsonar.projectKey=myorg_backend
          -Dsonar.projectName=myorg_backend
          -Dsonar.sources=.
          -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Debug Sonar secrets (backend)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        if [ -z "$SONAR_TOKEN" ]; then echo "SONAR_TOKEN missing"; else echo "SONAR_TOKEN OK"; fi
        if [ -z "$SONAR_HOST_URL" ]; then echo "SONAR_HOST_URL missing"; else echo "SONAR_HOST_URL OK"; fi

